// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SSDepartmentCore.Data;
using System;

namespace SSDepartmentCore.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180130000457_adding user entity")]
    partial class addinguserentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SSDepartmentCore.Data.EntityModels.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<bool>("Adventist");

                    b.Property<string>("Church");

                    b.Property<string>("ContactNumber");

                    b.Property<DateTime>("DateVisited");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("NeedCounselling");

                    b.Property<string>("Password");

                    b.Property<string>("PrayerRequest");

                    b.Property<bool>("SeePastor");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Visitors");
                });
#pragma warning restore 612, 618
        }
    }
}
